#!/usr/bin/env bash
# T7 — Interview coverage: bootstrap-prompt.md covers R5.2 minimum topic set (AC7).
set -uo pipefail

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=helpers/setup.bash
source "${SELF_DIR}/helpers/setup.bash"

# ── Tests — static assertions against the bootstrap prompt ────────────────────

_get_prompt() {
    # Try the prompts/ dir first; fall back to checking if a prompts dir exists.
    local _prompt_file="${REPO_ROOT}/prompts/bootstrap-prompt.md"
    if [[ -f "$_prompt_file" ]]; then
        cat "$_prompt_file"
    else
        echo ""
    fi
}

test_bootstrap_prompt_file_exists() {
    local _prompt="${REPO_ROOT}/prompts/bootstrap-prompt.md"
    if [[ ! -f "$_prompt" ]]; then
        _SKIP_REASON="prompts/bootstrap-prompt.md not found (generated by agent at runtime)"
        return 0
    fi
    return 0
}

test_prompt_covers_container_base_topic() {
    local _content
    _content="$(_get_prompt)"
    [[ -n "$_content" ]] || { _SKIP_REASON="bootstrap-prompt.md not present"; return 0; }
    local _found=0
    [[ "$_content" == *"base image"* || "$_content" == *"FROM"* || "$_content" == *"Containerfile"* ]] && _found=1
    [[ "$_found" -eq 1 ]] || {
        printf '    bootstrap-prompt.md should cover container base/FROM/Containerfile\n' >&2
        return 1
    }
}

test_prompt_covers_language_runtime() {
    local _content
    _content="$(_get_prompt)"
    [[ -n "$_content" ]] || { _SKIP_REASON="bootstrap-prompt.md not present"; return 0; }
    local _found=0
    [[ "$_content" == *"language"* || "$_content" == *"runtime"* || "$_content" == *"stack"* ]] && _found=1
    [[ "$_found" -eq 1 ]] || {
        printf '    bootstrap-prompt.md should cover language/runtime/stack\n' >&2
        return 1
    }
}

test_prompt_steers_secrets_to_runtime_mounting() {
    local _content
    _content="$(_get_prompt)"
    [[ -n "$_content" ]] || { _SKIP_REASON="bootstrap-prompt.md not present"; return 0; }
    local _found=0
    [[ "$_content" == *"secret"* || "$_content" == *"credential"* || "$_content" == *"API key"* ]] && _found=1
    [[ "$_content" == *"mount"* || "$_content" == *"env"* || "$_content" == *"runtime"* ]] && _found=$(( _found + 1 ))
    [[ "$_found" -ge 1 ]] || {
        printf '    bootstrap-prompt.md should address secrets and runtime mounting\n' >&2
        return 1
    }
}

test_start_here_places_prompt_in_bootstrap_dir() {
    # start-here.sh should copy the prompt from /start-here-prompts/ to bootstrap/.
    local _sh="${REPO_ROOT}/start-here.sh"
    [[ -f "$_sh" ]] || { printf '    start-here.sh not found\n' >&2; return 1; }
    if ! grep -q 'bootstrap-prompt.md' "$_sh"; then
        printf '    start-here.sh should reference bootstrap-prompt.md\n' >&2
        return 1
    fi
    return 0
}

test_no_hardcoded_questionnaire_in_start_here() {
    # start-here.sh should not contain a hardcoded Q&A questionnaire.
    local _sh="${REPO_ROOT}/start-here.sh"
    [[ -f "$_sh" ]] || { _SKIP_REASON="start-here.sh not found"; return 0; }

    local _q_count
    _q_count="$(grep -cE 'What (is|are) your|What (language|framework)|Which (language|framework)' "$_sh" 2>/dev/null || echo 0)"
    if [[ "$_q_count" -gt 3 ]]; then
        printf '    start-here.sh appears to have a hardcoded questionnaire (%d Q lines)\n' "$_q_count" >&2
        return 1
    fi
    return 0
}

test_session_md_records_interview_summary() {
    local _fail=0
    # Validate that session.md template has Interview Summary section.
    local _proj="${_TMPDIR}/projects/interviewtest"
    mkdir -p "${_proj}/bootstrap"
    cat > "${_proj}/bootstrap/agent.env" <<'AEOF'
# source_hash=abc
AGENT_NAME="codex"
AEOF
    cat > "${_TMPDIR}/interview_md_helper.sh" <<SCRIPT
#!/usr/bin/env bash
set -euo pipefail
source '${LIB_DIR}/common.sh'
source '${LIB_DIR}/session.sh'
export CODEX_JAILS_DIR='${_TMPDIR}'
init_session '${_proj}' 'interviewtest' 'codex'
cat '${_proj}/bootstrap/session.md'
SCRIPT
    local out rc=0
    out="$(bash "${_TMPDIR}/interview_md_helper.sh" 2>&1)" || rc=$?
    assert_success $rc || _fail=1
    assert_contains "Interview Summary" "$out" "session.md should have Interview Summary section" || _fail=1
    return $_fail
}

# ── Run ───────────────────────────────────────────────────────────────────────
run_test "bootstrap-prompt.md present (or skip)"               test_bootstrap_prompt_file_exists
run_test "prompt covers container base image topic"            test_prompt_covers_container_base_topic
run_test "prompt covers language/runtime stack topic"          test_prompt_covers_language_runtime
run_test "prompt steers secrets toward runtime mounting"        test_prompt_steers_secrets_to_runtime_mounting
run_test "start-here.sh references bootstrap-prompt.md"        test_start_here_places_prompt_in_bootstrap_dir
run_test "start-here.sh has no hardcoded questionnaire"        test_no_hardcoded_questionnaire_in_start_here
run_test "session.md template has Interview Summary section"   test_session_md_records_interview_summary

print_summary "test_interview_coverage"
